//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_final.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class Book_data
    {
        public int BOOK_ID { get; set; }
        [DisplayName("書籍名稱")]
        [Required]
        public string BOOK_NAME { get; set; }
       [DisplayName("書籍類別")]
        [Required]
        public string BOOK_CLASS_NAME { get; set; }
         [DisplayName("書籍作者")]
        public string BOOK_AUTHOR { get; set; }
        [DisplayName("購書日期")]
        public Nullable<System.DateTime> BOOK_BOUGHT_DATE { get; set; }
       [DisplayName("出版商")]
        public string BOOK_PUBLISHER { get; set; }
        [DisplayName("內容簡介")]
        public string BOOK_NOTE { get; set; }
           [DisplayName("借閱狀態")]
            [Required]
        public string BOOK_STATUS { get; set; }
      [DisplayName("借閱人")]
        
        public string BOOK_KEEPER { get; set; }
       


    }
    }


